name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ELIXIR_VERSION: 1.14.3
  OTP_VERSION: 25.2.2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  mix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: prepare
        uses: ./.github/workflows/prepare-ci

      - name: Install Dependencies
        run: mix do deps.get, deps.clean --unused

  build:
    runs-on: ubuntu-latest
    needs: mix
    steps:
      - uses: actions/checkout@v3

      - id: prepare
        uses: ./.github/workflows/prepare-ci

      - name: Check formatting
        run: mix format --check-formatted
      - name: Check warnings
        run: mix compile --warnings-as-errors

  test:
    runs-on: ubuntu-latest
    needs: mix
    services:
      pg:
        image: postgres:15.2-bullseye
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - id: prepare
        uses: ./.github/workflows/prepare-ci

      - name: "Set PG settings"
        run: |
          docker exec ${{ job.services.pg.id }} sh -c 'echo "wal_level=logical\nmax_wal_senders=10\nmax_replication_slots=10\n" >> /var/lib/postgresql/data/postgresql.conf'
          docker restart ${{ job.services.pg.id }}

      - name: Test
        run: mix test

  credo:
    runs-on: ubuntu-latest
    needs: mix
    steps:
      - uses: actions/checkout@v3

      - id: prepare
        uses: ./.github/workflows/prepare-ci

      - name: Credo
        run: mix credo --strict

  dialyzer:
    runs-on: ubuntu-latest
    needs: mix
    steps:
      - uses: actions/checkout@v3

      - id: prepare
        uses: ./.github/workflows/prepare-ci

      - uses: actions/cache@v3
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ hashFiles('.tool-versions') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-plt-${{ hashFiles('.tool-versions') }}-

      - name: Dialyzer
        run: mix dialyzer --format github
